### ISSUE TITLE
Fix environment variables

### ISSUE THREAD

**Issue by oxr463** [aad-for-linux/docker#8]
See: https://github.com/aad-for-linux/docker/blob/master/pam_aad/rocky/Dockerfile#L24

**Comment by outzhu** [comment]
just a random name  variable I did. Remember 
https://github.com/aad-for-linux/pam_aad/blob/master/docker/amazon/2018.03/Dockerfile#L36?

**Comment by oxr463** [comment]
> just a random name variable I did. Remember https://github.com/aad-for-linux/pam_aad/blob/master/docker/amazon/2018.03/Dockerfile#L36?

`PAMDIR` isn't random. It stands for PAM Directory, (See: https://github.com/linux-pam/linux-pam/issues/256).

We'll need to update that.

**Comment by outzhu** [comment]
should NSS_PATH also be changed back to LD_LIBRARY_PATH?

**Comment by oxr463** [comment]
> should NSS_PATH also be changed back to LD_LIBRARY_PATH?

Yes, that one is very important, (See: https://www.hpc.dtu.dk/?page_id=1180)
